### ISSUE TITLE
Assistant: Copilot Chat broken in latest builds

### ISSUE THREAD

**Issue by jmcphers** [posit-dev/positron#10566]
#### Positron and OS details:

```
Positron Version: 2025.12.0 build 72
Code - OSS Version: 1.105.0
Commit: 3af147dca07686d2cfa80faf0796c04661c56616
Date: 2025-11-14T07:19:22.022Z
Electron: 37.6.0
Chromium: 138.0.7204.251
Node.js: 22.19.0
V8: 13.8.258.32-electron.0
OS: Darwin arm64 25.1.0
```

#### Session details:

N/A

## Describe the issue:

Attempting to use Copilot Chat fails with the error:

```
positronEnabledTools.includes is not a function
```

<img width="428" height="322" alt="Image" src="https://github.com/user-attachments/assets/11585484-1c07-4d2d-97fa-37b6e2a05a55" />

## Expected or desired behavior:

Copilot Chat works.

This appears to be a regression from https://github.com/posit-dev/positron/pull/10440. This PR made the tool enablement check async:

https://github.com/posit-dev/positron/pull/10440/files#diff-aaeb769b158d713867a8cad05c5879c378c35030e44a1b8b680f74e82e249abeR146

but it's called from Copilot Chat, which doesn't handle asynchronous behavior.

**Comment by rodrigosf672** [comment]
### Verified Fixed
    Positron Version(s) : 2025.12.0 build 79
    OS Version          : macOS Tahoe 26.1

### Test scenario(s) 
- Copilot Chat is no longer broken.
