### PR TITLE
Bug fix revert get enabled tools to sync

### PR DESCRIPTION
**Pull request by nstrayer**
Addresses #10566.

This PR fixes a regression in Copilot Chat introduced by #10440, which made `getEnabledTools` asynchronous. Copilot Chat calls this function synchronously and doesn't handle promises, causing chat requests to fail with "positronEnabledTools.includes is not a function".

The fix reverts `getEnabledTools` to synchronous while maintaining the notebook awareness functionality by:
- Creating `isNotebookModeEnabled()` to synchronously check the workspace configuration
- Creating `extractAttachedNotebookUris()` to synchronously extract notebook URIs from request references
- Making `hasAttachedNotebookContext()` synchronous by checking if notebooks are attached without needing async operations

#### New Features
- N/A

#### Bug Fixes
- Fixed Copilot Chat failing with "positronEnabledTools.includes is not a function" error (#10566)

### QA Notes

@:assistant

1. Enable GitHub Copilot Chat in Positron
2. Open a chat session with Copilot
3. Send a message to verify chat works without errors
4. Optional: Test with a Positron notebook attached to verify notebook context still works:
   - Open a `.ipynb` file
   - Attach it to the chat context
   - Send a message and verify notebook-specific tools are available

### CODE REVIEW

**Review by jmcphers — CHANGES_REQUESTED** [review]
This did not work for me.

image

The Copilot Chat extension does not call `getEnabledTools` directly -- it calls it via the API, which is still marked `async`. 

This change also generates some warnings since a number of places are still calling `await` on `getEnabledTools` (including the aforementioned)

**Review by jmcphers — APPROVED** [review]
Working for me after https://github.com/posit-dev/positron/pull/10577/commits/4dd687d116d3f92592368e50f4b51bc27048819d!
